services:
  ms-cart-database:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=ms-cart
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ms-cart-network

volumes:
  postgres_data:

networks:
  ms-cart-network:
