services:
  ms-user-database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ms-user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ms-user-network

volumes:
  postgres_data:

networks:
  ms-user-network:
